---
- hosts: all
  vars:
    mfts_timezone: "UTC"
    mfts_sysctl_rules: []
    mfts_setup_directory: []
    mfts_copy_files: []
    mfts_command_after_copyfiles: []
    mfts_lineinfile_after_copyfiles: []
    mfts_additional_packages:
      - keepalived
      - linux-generic-hwe-22.04
      - lm-sensors
      - lvm2
      - make
      - nmon
      - openntpd
      - python3
      - python3-dev
      - python3-venv
      - ruby
      - smartmontools
      - tcpdump
    mfts_remove_packages: []
    mfts_copy_files_after_packages:
      - { src: "{{ inventory_dir }}/files/keepalived/gen-lbconf.conf", dest: "/etc/keepalived/gen-lbconf.conf", owner: "root", group: "root", mode: "0644" }
      - { src: "{{ inventory_dir }}/files/keepalived/gen-lbconf.rb", dest: "/etc/keepalived/gen-lbconf.rb", owner: "root", group: "root", mode: "0750" }
      - { src: "{{ inventory_dir }}/files/keepalived/keepalived.conf.tmpl", dest: "/etc/keepalived/keepalived.conf.tmpl", owner: "root", group: "root", mode: "0644" }
    mfts_lineinfile_after_packages: []
    mfts_command_after_packages:
      - { command: "/etc/keepalived/gen-lbconf.rb /etc/keepalived/gen-lbconf.conf /etc/keepalived/keepalived.conf.tmpl > /etc/keepalived/keepalived.conf", become: "yes" }
    mfts_systemd_rules:
      - { name: "keepalived.service", state: "restarted", enabled: "yes", daemon_reload: "yes" }
  roles:
    - YasuhiroABE.myfavorite-setting



